version: '2'
services:
  cadvisor:
    image: google/cadvisor
    ports:
      - "8000:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
     - artifactory
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    ports:
      - "8081:8081"
    networks:
      - artifactory
    env_file:
      - container.env
    volumes:
      - ./data:/var/opt/jfrog/artifactory/data
      - ./logs:/var/opt/jfrog/artifactory/logs
      - ./etc:/var/opt/jfrog/artifactory/etc
  httpd:
   image: automation-tools-us1p.dev.power.ge.com/pwr-it/httpd-oprnid-sslconf:latest
   env_file:
     - container.env
     - base.env
   volumes:
    - "./ssl:/usr/local/apache2/conf/ssl"
   ports:
    - "80:80"
    - "443:443"
   networks:
    - artifactory
   links:
    - artifactory:artifactory
    - cadvisor:cadvisor
networks:
  artifactory:
    driver: bridge
